name: Nix Simple Cache Action
description: cache the nix store
author: Trev
branding:
  icon: chevron-up
  color: yellow

outputs:
  cache-hit:
    description: A string value to indicate if the cache was found.

runs:
  using: node24
  main: dist/start.js
  post: dist/cleanup.js
