name: 'init'
description: 'initialize nix'
runs:
  using: 'composite'
  steps:
    - uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      with:
        extra-conf: |
          extra-substituters = https://trevnur.cachix.org
          extra-trusted-public-keys = trevnur.cachix.org-1:hBd15IdszwT52aOxdKs5vNTbq36emvEeGqpb25Bkq6o=

    - uses: ./

    - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
