name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@b1a572723d705a405747541fad38545a57f03ee3 # v1.7.0
        with:
          shell: ci
          fetch_depth: 0
          app_id: ${{ vars.CLIENT_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Bump
        uses: spotdemo4/bumper@32534ba92eb765a5dd0d22d2ee2064748d0a2042 # v0.2.5
        with:
          files: |-
            .github/README.md
