name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@db355b991de421e07d3c89f9edc18ef8f71394ea # v1.3.0
        with:
          shell: ci
          fetch_depth: 0
          app_id: ${{ vars.CLIENT_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Bump
        uses: spotdemo4/bumper@8b9df22ba64a8cbc777429d5e96fedc6e6346c6c # v0.2.3
        with:
          files: |-
            .github/README.md
