name: check

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@08a91698a7d25d7492b4883a37cd889db53353b1 # v1.0.2

      - name: Run checks
        run: nix flake check

