name: check

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: spotdemo4/nix-simple-cache-action/.github/actions/init@main

      - run: nix flake check -L
      - run: nix build .# --no-link --print-out-paths
