name: check

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
        with:
          extra-conf: |
            accept-flake-config = true
            download-buffer-size = 524288000

      - uses: spotdemo4/nix-simple-cache-action@main

      - name: Run checks
        run: nix flake check

